name: Fetch JSON Data

on:
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Fetch JSON data
        run: |
          curl https://api.dabing.one?whiteboard_id=09dba888a0c5beb7cadcb74ac8ffe96c52197df0de63eac2da86f6ea12c86fa5 > src/resources/data.json

      - name: Save JSON data to repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout -B main 
          git pull
          git add src/resources/data.json  # Change data.`json to data.json
          git commit -m "Update data.json"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
